import payload from "../../generated-assets-list-module.js"

const registerServiceWorker = async () => {
  if (!navigator.serviceWorker) return;
  try {
    await navigator.serviceWorker.register('/service-worker.js')
    console.log('Service Worker Registered');
    //inject the static assets generated by `node node-scripts/generateAssetsList.js` 
    navigator.serviceWorker.controller.postMessage({ type: "ASSET_PATHS", payload })
  } catch (error) {
    console.log('Service Worker Registration Failed', error);
  }
}

registerServiceWorker()